runtime: python39

handlers:
  # Serve /azlan with redirect HTML
  - url: /azlan
    static_files: build/azlan.html
    upload: build/azlan.html

  # Also handle /azlan/
  - url: /azlan/
    static_files: build/azlan.html
    upload: build/azlan.html

  # Serve static assets (CSS, JS, images)
  - url: /assets/(.*)
    static_files: build/assets/\1
    upload: build/assets/.*

  # Serve the main HTML file for all other routes (SPA routing)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html